global:
  redis:
    addrs:
      - redis-master.tyk.svc.cluster.local:6379
    pass: ""

tyk-gateway:
  gateway:
    replicaCount: 1
    opentelemetry:
      enabled: true
      exporter: grpc
      endpoint: datadog-otel.datadog.svc.cluster.local:4317
      connectionTimeout: 10
      spanProcessorType: simple
      samplingType: AlwaysOn
      contextPropagation: tracecontext

    extraEnvs:
      - name: OTEL_K8S_POD_UID
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
      - name: OTEL_K8S_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "k8s.pod.uid=$(OTEL_K8S_POD_UID),k8s.pod.ip=$(OTEL_K8S_POD_IP),k8s.container.name=gateway-tyk-gateway"

    service:
      type: LoadBalancer
      port: 8080
      targetPort: 8080
